In [1]:
#Import all required libraries for reading data, analysing and visualizing data
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.preprocessing import LabelEncoder

In [2]:
liver_df = pd.read_csv('indian_liver_patient.csv')

In [3]:
liver_df.loc[1]

Age                             62
Gender                        Male
Total_Bilirubin               10.9
Direct_Bilirubin               5.5
Alkaline_Phosphotase           699
Alamine_Aminotransferase        64
Aspartate_Aminotransferase     100
Total_Protiens                 7.5
Albumin                        3.2
Albumin_and_Globulin_Ratio    0.74
Dataset                          1
Name: 1, dtype: object

In [3]:
#liver_df = pd.concat([liver_df,pd.get_dummies(liver_df['Gender'], prefix = 'Gender')], axis=1)

In [4]:
liver_df.head()

Age  Gender  Total_Bilirubin  Direct_Bilirubin  Alkaline_Phosphotase  \
0   65  Female              0.7               0.1                   187   
1   62    Male             10.9               5.5                   699   
2   62    Male              7.3               4.1                   490   
3   58    Male              1.0               0.4                   182   
4   72    Male              3.9               2.0                   195   

   Alamine_Aminotransferase  Aspartate_Aminotransferase  Total_Protiens  \
0                        16                          18             6.8   
1                        64                         100             7.5   
2                        60                          68             7.0   
3                        14                          20             6.8   
4                        27                          59             7.3   

   Albumin  Albumin_and_Globulin_Ratio  Dataset  
0      3.3                        0.90        1  
1      3.2                        0.74        1  
2      3.3                        0.89        1  
3      3.4                        1.00        1  
4      2.4                        0.40        1

In [4]:
liver_df["Albumin_and_Globulin_Ratio"] = liver_df.Albumin_and_Globulin_Ratio.fillna(liver_df['Albumin_and_Globulin_Ratio'].mean())

In [5]:
gender = {'Male': 1,'Female': 2} 
liver_df.Gender = [gender[item] for item in liver_df.Gender] 
X = liver_df.drop('Dataset', axis=1)
X = (X - np.min(X)) / (np.max(X) - np.min(X)).values

In [6]:
y = liver_df['Dataset']

In [8]:
# Importing modules
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)


In [10]:
linear = linear_model.LinearRegression()
# Train the model using the training sets and check score
linear.fit(X_train, y_train)
#Predict Output
lin_predicted = linear.predict(X_test)

linear_score = round(linear.score(X_train, y_train) * 100, 2)
linear_score_test = round(linear.score(X_test, y_test) * 100, 2)
#Equation coefficient and Intercept
print('Linear Regression Score: \n', linear_score)
print('Linear Regression Test Score: \n', linear_score_test)
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

from sklearn.feature_selection import RFE
rfe =RFE(linear, n_features_to_select=3)
rfe.fit(X,y)

Linear Regression Score: 
 13.12
Linear Regression Test Score: 
 8.07
Coefficient: 
 [-0.21787113  0.09227434 -0.03004706 -0.45013128 -0.44523972 -0.78216528
  0.30129108 -0.383512    0.38227101  0.15552493]
Intercept: 
 1.4618887074758427


RFE(estimator=LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False),
  n_features_to_select=3, step=1, verbose=0)

In [11]:
for i in range(len(rfe.ranking_)):
    if rfe.ranking_[i] == 1:
        print(X.columns.values[i])

Direct_Bilirubin
Alamine_Aminotransferase
Albumin


In [12]:
finX = liver_df[['Total_Protiens','Albumin', 'Gender']]


In [13]:

X_train, X_test, y_train, y_test = train_test_split(finX, y, test_size=0.20, random_state=101)

In [14]:
#Logistic Regression
logreg = LogisticRegression()
# Train the model using the training sets and check score
logreg.fit(X_train,y_train)
#Predict Output
log_predicted= logreg.predict(X_test)

logreg_score = round(logreg.score(X_train, y_train) * 100, 2)
logreg_score_test = round(logreg.score(X_test, y_test) * 100, 2)
#Equation coefficient and Intercept
print('Logistic Regression Training Score: \n', logreg_score)
print('Logistic Regression Test Score: \n', logreg_score_test)
print('Coefficient: \n', logreg.coef_)
print('Intercept: \n', logreg.intercept_)
print('Accuracy: \n', accuracy_score(y_test,log_predicted))
print('Confusion Matrix: \n', confusion_matrix(y_test,log_predicted))
print('Classification Report: \n', classification_report(y_test,log_predicted))

#sns.heatmap(confusion_matrix(y_test,log_predicted),annot=True,fmt="d")


Logistic Regression Training Score: 
 71.03
Logistic Regression Test Score: 
 70.94
Coefficient: 
 [[-0.6482642   1.08808635  0.46640492]]
Intercept: 
 [-0.7458016]
Accuracy: 
 0.7094017094017094
Confusion Matrix: 
 [[81  3]
 [31  2]]
Classification Report: 
               precision    recall  f1-score   support

           1       0.72      0.96      0.83        84
           2       0.40      0.06      0.11        33

   micro avg       0.71      0.71      0.71       117
   macro avg       0.56      0.51      0.47       117
weighted avg       0.63      0.71      0.62       117



/home/iamshankhadeep/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [15]:
# Random Forest

random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
#Predict Output
rf_predicted = random_forest.predict(X_test)

random_forest_score = round(random_forest.score(X_train, y_train) * 100, 2)
random_forest_score_test = round(random_forest.score(X_test, y_test) * 100, 2)
print('Random Forest Score: \n', random_forest_score)
print('Random Forest Test Score: \n', random_forest_score_test)
print('Accuracy: \n', accuracy_score(y_test,rf_predicted))
print(confusion_matrix(y_test,rf_predicted))
print(classification_report(y_test,rf_predicted))

Random Forest Score: 
 92.27
Random Forest Test Score: 
 65.81
Accuracy: 
 0.6581196581196581
[[71 13]
 [27  6]]
              precision    recall  f1-score   support

           1       0.72      0.85      0.78        84
           2       0.32      0.18      0.23        33

   micro avg       0.66      0.66      0.66       117
   macro avg       0.52      0.51      0.51       117
weighted avg       0.61      0.66      0.63       117



In [16]:
from sklearn.externals import joblib


In [17]:
joblib.dump(logreg, 'logreg.pkl') 

['logreg.pkl']